# flake8: noqa
"""empty message

Revision ID: 1787d27cfda
Revises: 25105859b5b
Create Date: 2015-08-21 11:25:08.558114

"""

# revision identifiers, used by Alembic.
revision = '1787d27cfda'
down_revision = '25105859b5b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def __new_uuid():
    return str(uuid.uuid4().hex[:7]).lower()


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity', sa.Column('token', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity', 'token')
    ### end Alembic commands ###
