# flake8: noqa
"""empty message

Revision ID: 25105859b5b
Revises: bc31543a82
Create Date: 2015-08-21 10:38:21.611069

"""

# revision identifiers, used by Alembic.
revision = '25105859b5b'
down_revision = 'bc31543a82'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity', sa.Column('address_line1', sa.String(), nullable=True))
    op.add_column('identity', sa.Column('address_line2', sa.String(), nullable=True))
    op.add_column('identity', sa.Column('address_line3', sa.String(), nullable=True))
    op.add_column('identity', sa.Column('address_line4', sa.String(), nullable=True))
    op.add_column('identity', sa.Column('address_line5', sa.String(), nullable=True))
    op.add_column('identity', sa.Column('dob', sa.String(), nullable=True))
    op.add_column('identity', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('identity', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('identity', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('identity', sa.Column('middle_names', sa.String(), nullable=True))
    op.add_column('identity', sa.Column('postcode', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity', 'postcode')
    op.drop_column('identity', 'middle_names')
    op.drop_column('identity', 'last_name')
    op.drop_column('identity', 'gender')
    op.drop_column('identity', 'first_name')
    op.drop_column('identity', 'dob')
    op.drop_column('identity', 'address_line5')
    op.drop_column('identity', 'address_line4')
    op.drop_column('identity', 'address_line3')
    op.drop_column('identity', 'address_line2')
    op.drop_column('identity', 'address_line1')
    ### end Alembic commands ###
