# flake8: noqa
"""empty message

Revision ID: bc31543a82
Revises: 
Create Date: 2015-08-17 14:50:00.228980

"""

# revision identifiers, used by Alembic.
revision = 'bc31543a82'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity')
    ### end Alembic commands ###
